// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frinmxtouewkvfbxgsqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaW5teHRvdWV3a3ZmYnhnc3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzE2ODIsImV4cCI6MjA2NTUwNzY4Mn0.8tppFDGjue-MznlRHqBq77c_h1X3C0OaWbL90MY0Iek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);